// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.0
// source: meals-pkg-models.proto

package meals_pkg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Meal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MealUuid     []byte        `protobuf:"bytes,1,opt,name=meal_uuid,json=mealUuid,proto3" json:"meal_uuid,omitempty"`
	Name         string        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description  string        `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price        float32       `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	MealSettings *MealSettings `protobuf:"bytes,5,opt,name=meal_settings,json=mealSettings,proto3" json:"meal_settings,omitempty"`
	MealAny      []byte        `protobuf:"bytes,6,opt,name=meal_any,json=mealAny,proto3" json:"meal_any,omitempty"`
}

func (x *Meal) Reset() {
	*x = Meal{}
	mi := &file_meals_pkg_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Meal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meal) ProtoMessage() {}

func (x *Meal) ProtoReflect() protoreflect.Message {
	mi := &file_meals_pkg_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meal.ProtoReflect.Descriptor instead.
func (*Meal) Descriptor() ([]byte, []int) {
	return file_meals_pkg_models_proto_rawDescGZIP(), []int{0}
}

func (x *Meal) GetMealUuid() []byte {
	if x != nil {
		return x.MealUuid
	}
	return nil
}

func (x *Meal) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Meal) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Meal) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Meal) GetMealSettings() *MealSettings {
	if x != nil {
		return x.MealSettings
	}
	return nil
}

func (x *Meal) GetMealAny() []byte {
	if x != nil {
		return x.MealAny
	}
	return nil
}

type MealSettings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MealSettings) Reset() {
	*x = MealSettings{}
	mi := &file_meals_pkg_models_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MealSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MealSettings) ProtoMessage() {}

func (x *MealSettings) ProtoReflect() protoreflect.Message {
	mi := &file_meals_pkg_models_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MealSettings.ProtoReflect.Descriptor instead.
func (*MealSettings) Descriptor() ([]byte, []int) {
	return file_meals_pkg_models_proto_rawDescGZIP(), []int{1}
}

type Meals struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Meals []*Meal `protobuf:"bytes,1,rep,name=Meals,proto3" json:"Meals,omitempty"`
}

func (x *Meals) Reset() {
	*x = Meals{}
	mi := &file_meals_pkg_models_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Meals) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meals) ProtoMessage() {}

func (x *Meals) ProtoReflect() protoreflect.Message {
	mi := &file_meals_pkg_models_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meals.ProtoReflect.Descriptor instead.
func (*Meals) Descriptor() ([]byte, []int) {
	return file_meals_pkg_models_proto_rawDescGZIP(), []int{2}
}

func (x *Meals) GetMeals() []*Meal {
	if x != nil {
		return x.Meals
	}
	return nil
}

var File_meals_pkg_models_proto protoreflect.FileDescriptor

var file_meals_pkg_models_proto_rawDesc = []byte{
	0x0a, 0x16, 0x6d, 0x65, 0x61, 0x6c, 0x73, 0x2d, 0x70, 0x6b, 0x67, 0x2d, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73,
	0x22, 0xc5, 0x01, 0x0a, 0x04, 0x4d, 0x65, 0x61, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x65, 0x61,
	0x6c, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x6d, 0x65,
	0x61, 0x6c, 0x55, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x12, 0x39, 0x0a, 0x0d, 0x6d, 0x65, 0x61, 0x6c, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x2e, 0x4d, 0x65, 0x61, 0x6c, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52,
	0x0c, 0x6d, 0x65, 0x61, 0x6c, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x19, 0x0a,
	0x08, 0x6d, 0x65, 0x61, 0x6c, 0x5f, 0x61, 0x6e, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x6d, 0x65, 0x61, 0x6c, 0x41, 0x6e, 0x79, 0x22, 0x0e, 0x0a, 0x0c, 0x4d, 0x65, 0x61, 0x6c,
	0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x2b, 0x0a, 0x05, 0x4d, 0x65, 0x61, 0x6c,
	0x73, 0x12, 0x22, 0x0a, 0x05, 0x4d, 0x65, 0x61, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x4d, 0x65, 0x61, 0x6c, 0x52, 0x05,
	0x4d, 0x65, 0x61, 0x6c, 0x73, 0x42, 0x15, 0x5a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x73, 0x2f, 0x6d, 0x65, 0x61, 0x6c, 0x73, 0x2d, 0x70, 0x6b, 0x67, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_meals_pkg_models_proto_rawDescOnce sync.Once
	file_meals_pkg_models_proto_rawDescData = file_meals_pkg_models_proto_rawDesc
)

func file_meals_pkg_models_proto_rawDescGZIP() []byte {
	file_meals_pkg_models_proto_rawDescOnce.Do(func() {
		file_meals_pkg_models_proto_rawDescData = protoimpl.X.CompressGZIP(file_meals_pkg_models_proto_rawDescData)
	})
	return file_meals_pkg_models_proto_rawDescData
}

var file_meals_pkg_models_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_meals_pkg_models_proto_goTypes = []any{
	(*Meal)(nil),         // 0: models.Meal
	(*MealSettings)(nil), // 1: models.MealSettings
	(*Meals)(nil),        // 2: models.Meals
}
var file_meals_pkg_models_proto_depIdxs = []int32{
	1, // 0: models.Meal.meal_settings:type_name -> models.MealSettings
	0, // 1: models.Meals.Meals:type_name -> models.Meal
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_meals_pkg_models_proto_init() }
func file_meals_pkg_models_proto_init() {
	if File_meals_pkg_models_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_meals_pkg_models_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meals_pkg_models_proto_goTypes,
		DependencyIndexes: file_meals_pkg_models_proto_depIdxs,
		MessageInfos:      file_meals_pkg_models_proto_msgTypes,
	}.Build()
	File_meals_pkg_models_proto = out.File
	file_meals_pkg_models_proto_rawDesc = nil
	file_meals_pkg_models_proto_goTypes = nil
	file_meals_pkg_models_proto_depIdxs = nil
}
