// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.0
// source: meals-pkg-service.proto

package meals_pkg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MealDeleteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MealUuid []byte `protobuf:"bytes,1,opt,name=meal_uuid,json=mealUuid,proto3" json:"meal_uuid,omitempty"`
}

func (x *MealDeleteReq) Reset() {
	*x = MealDeleteReq{}
	mi := &file_meals_pkg_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MealDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MealDeleteReq) ProtoMessage() {}

func (x *MealDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_meals_pkg_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MealDeleteReq.ProtoReflect.Descriptor instead.
func (*MealDeleteReq) Descriptor() ([]byte, []int) {
	return file_meals_pkg_service_proto_rawDescGZIP(), []int{0}
}

func (x *MealDeleteReq) GetMealUuid() []byte {
	if x != nil {
		return x.MealUuid
	}
	return nil
}

type MealsEmpty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MealsEmpty) Reset() {
	*x = MealsEmpty{}
	mi := &file_meals_pkg_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MealsEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MealsEmpty) ProtoMessage() {}

func (x *MealsEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_meals_pkg_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MealsEmpty.ProtoReflect.Descriptor instead.
func (*MealsEmpty) Descriptor() ([]byte, []int) {
	return file_meals_pkg_service_proto_rawDescGZIP(), []int{1}
}

type MealGetter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Getter:
	//
	//	*MealGetter_Uuid
	//	*MealGetter_Name
	Getter isMealGetter_Getter `protobuf_oneof:"getter"`
}

func (x *MealGetter) Reset() {
	*x = MealGetter{}
	mi := &file_meals_pkg_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MealGetter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MealGetter) ProtoMessage() {}

func (x *MealGetter) ProtoReflect() protoreflect.Message {
	mi := &file_meals_pkg_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MealGetter.ProtoReflect.Descriptor instead.
func (*MealGetter) Descriptor() ([]byte, []int) {
	return file_meals_pkg_service_proto_rawDescGZIP(), []int{2}
}

func (m *MealGetter) GetGetter() isMealGetter_Getter {
	if m != nil {
		return m.Getter
	}
	return nil
}

func (x *MealGetter) GetUuid() []byte {
	if x, ok := x.GetGetter().(*MealGetter_Uuid); ok {
		return x.Uuid
	}
	return nil
}

func (x *MealGetter) GetName() string {
	if x, ok := x.GetGetter().(*MealGetter_Name); ok {
		return x.Name
	}
	return ""
}

type isMealGetter_Getter interface {
	isMealGetter_Getter()
}

type MealGetter_Uuid struct {
	Uuid []byte `protobuf:"bytes,1,opt,name=uuid,proto3,oneof"`
}

type MealGetter_Name struct {
	Name string `protobuf:"bytes,2,opt,name=name,proto3,oneof"`
}

func (*MealGetter_Uuid) isMealGetter_Getter() {}

func (*MealGetter_Name) isMealGetter_Getter() {}

var File_meals_pkg_service_proto protoreflect.FileDescriptor

var file_meals_pkg_service_proto_rawDesc = []byte{
	0x0a, 0x17, 0x6d, 0x65, 0x61, 0x6c, 0x73, 0x2d, 0x70, 0x6b, 0x67, 0x2d, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x1a, 0x16, 0x6d, 0x65, 0x61, 0x6c, 0x73, 0x2d, 0x70, 0x6b, 0x67, 0x2d, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2c, 0x0a, 0x0d, 0x4d, 0x65, 0x61,
	0x6c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x65,
	0x61, 0x6c, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x6d,
	0x65, 0x61, 0x6c, 0x55, 0x75, 0x69, 0x64, 0x22, 0x0c, 0x0a, 0x0a, 0x4d, 0x65, 0x61, 0x6c, 0x73,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x42, 0x0a, 0x0a, 0x4d, 0x65, 0x61, 0x6c, 0x47, 0x65, 0x74,
	0x74, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x48, 0x00, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x42,
	0x08, 0x0a, 0x06, 0x67, 0x65, 0x74, 0x74, 0x65, 0x72, 0x32, 0xe0, 0x01, 0x0a, 0x0c, 0x4d, 0x65,
	0x61, 0x6c, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x13, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x61, 0x6c,
	0x73, 0x12, 0x0d, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x4d, 0x65, 0x61, 0x6c, 0x73,
	0x1a, 0x12, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x4d, 0x65, 0x61, 0x6c, 0x73, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x12, 0x2d, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x61, 0x6c, 0x73,
	0x12, 0x12, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x4d, 0x65, 0x61, 0x6c, 0x73, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0d, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x4d, 0x65,
	0x61, 0x6c, 0x73, 0x12, 0x2e, 0x0a, 0x0a, 0x4d, 0x65, 0x61, 0x6c, 0x42, 0x79, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x12, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x4d, 0x65, 0x61, 0x6c, 0x47,
	0x65, 0x74, 0x74, 0x65, 0x72, 0x1a, 0x0c, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x4d,
	0x65, 0x61, 0x6c, 0x12, 0x37, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x61,
	0x6c, 0x12, 0x15, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x4d, 0x65, 0x61, 0x6c, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x2e, 0x4d, 0x65, 0x61, 0x6c, 0x73, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x15, 0x5a, 0x13,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2f, 0x6d, 0x65, 0x61, 0x6c, 0x73, 0x2d,
	0x70, 0x6b, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_meals_pkg_service_proto_rawDescOnce sync.Once
	file_meals_pkg_service_proto_rawDescData = file_meals_pkg_service_proto_rawDesc
)

func file_meals_pkg_service_proto_rawDescGZIP() []byte {
	file_meals_pkg_service_proto_rawDescOnce.Do(func() {
		file_meals_pkg_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_meals_pkg_service_proto_rawDescData)
	})
	return file_meals_pkg_service_proto_rawDescData
}

var file_meals_pkg_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_meals_pkg_service_proto_goTypes = []any{
	(*MealDeleteReq)(nil), // 0: models.MealDeleteReq
	(*MealsEmpty)(nil),    // 1: models.MealsEmpty
	(*MealGetter)(nil),    // 2: models.MealGetter
	(*Meals)(nil),         // 3: models.Meals
	(*Meal)(nil),          // 4: models.Meal
}
var file_meals_pkg_service_proto_depIdxs = []int32{
	3, // 0: models.MealsService.CreateOrUpdateMeals:input_type -> models.Meals
	1, // 1: models.MealsService.GetMeals:input_type -> models.MealsEmpty
	2, // 2: models.MealsService.MealByName:input_type -> models.MealGetter
	0, // 3: models.MealsService.DeleteMeal:input_type -> models.MealDeleteReq
	1, // 4: models.MealsService.CreateOrUpdateMeals:output_type -> models.MealsEmpty
	3, // 5: models.MealsService.GetMeals:output_type -> models.Meals
	4, // 6: models.MealsService.MealByName:output_type -> models.Meal
	1, // 7: models.MealsService.DeleteMeal:output_type -> models.MealsEmpty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_meals_pkg_service_proto_init() }
func file_meals_pkg_service_proto_init() {
	if File_meals_pkg_service_proto != nil {
		return
	}
	file_meals_pkg_models_proto_init()
	file_meals_pkg_service_proto_msgTypes[2].OneofWrappers = []any{
		(*MealGetter_Uuid)(nil),
		(*MealGetter_Name)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_meals_pkg_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_meals_pkg_service_proto_goTypes,
		DependencyIndexes: file_meals_pkg_service_proto_depIdxs,
		MessageInfos:      file_meals_pkg_service_proto_msgTypes,
	}.Build()
	File_meals_pkg_service_proto = out.File
	file_meals_pkg_service_proto_rawDesc = nil
	file_meals_pkg_service_proto_goTypes = nil
	file_meals_pkg_service_proto_depIdxs = nil
}
