// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: meals-pkg-models.proto

package meals_pkg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Meal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MealUuid      []byte                 `protobuf:"bytes,1,opt,name=meal_uuid,json=mealUuid,proto3" json:"meal_uuid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float32                `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	MealSettings  []byte                 `protobuf:"bytes,5,opt,name=meal_settings,json=mealSettings,proto3" json:"meal_settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Meal) Reset() {
	*x = Meal{}
	mi := &file_meals_pkg_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Meal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meal) ProtoMessage() {}

func (x *Meal) ProtoReflect() protoreflect.Message {
	mi := &file_meals_pkg_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meal.ProtoReflect.Descriptor instead.
func (*Meal) Descriptor() ([]byte, []int) {
	return file_meals_pkg_models_proto_rawDescGZIP(), []int{0}
}

func (x *Meal) GetMealUuid() []byte {
	if x != nil {
		return x.MealUuid
	}
	return nil
}

func (x *Meal) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Meal) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Meal) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Meal) GetMealSettings() []byte {
	if x != nil {
		return x.MealSettings
	}
	return nil
}

type Meals struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meals         []*Meal                `protobuf:"bytes,1,rep,name=Meals,proto3" json:"Meals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Meals) Reset() {
	*x = Meals{}
	mi := &file_meals_pkg_models_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Meals) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meals) ProtoMessage() {}

func (x *Meals) ProtoReflect() protoreflect.Message {
	mi := &file_meals_pkg_models_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meals.ProtoReflect.Descriptor instead.
func (*Meals) Descriptor() ([]byte, []int) {
	return file_meals_pkg_models_proto_rawDescGZIP(), []int{1}
}

func (x *Meals) GetMeals() []*Meal {
	if x != nil {
		return x.Meals
	}
	return nil
}

var File_meals_pkg_models_proto protoreflect.FileDescriptor

const file_meals_pkg_models_proto_rawDesc = "" +
	"\n" +
	"\x16meals-pkg-models.proto\x12\x06models\"\x94\x01\n" +
	"\x04Meal\x12\x1b\n" +
	"\tmeal_uuid\x18\x01 \x01(\fR\bmealUuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x02R\x05price\x12#\n" +
	"\rmeal_settings\x18\x05 \x01(\fR\fmealSettings\"+\n" +
	"\x05Meals\x12\"\n" +
	"\x05Meals\x18\x01 \x03(\v2\f.models.MealR\x05MealsB\x15Z\x13protocols/meals-pkgb\x06proto3"

var (
	file_meals_pkg_models_proto_rawDescOnce sync.Once
	file_meals_pkg_models_proto_rawDescData []byte
)

func file_meals_pkg_models_proto_rawDescGZIP() []byte {
	file_meals_pkg_models_proto_rawDescOnce.Do(func() {
		file_meals_pkg_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meals_pkg_models_proto_rawDesc), len(file_meals_pkg_models_proto_rawDesc)))
	})
	return file_meals_pkg_models_proto_rawDescData
}

var file_meals_pkg_models_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_meals_pkg_models_proto_goTypes = []any{
	(*Meal)(nil),  // 0: models.Meal
	(*Meals)(nil), // 1: models.Meals
}
var file_meals_pkg_models_proto_depIdxs = []int32{
	0, // 0: models.Meals.Meals:type_name -> models.Meal
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_meals_pkg_models_proto_init() }
func file_meals_pkg_models_proto_init() {
	if File_meals_pkg_models_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meals_pkg_models_proto_rawDesc), len(file_meals_pkg_models_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meals_pkg_models_proto_goTypes,
		DependencyIndexes: file_meals_pkg_models_proto_depIdxs,
		MessageInfos:      file_meals_pkg_models_proto_msgTypes,
	}.Build()
	File_meals_pkg_models_proto = out.File
	file_meals_pkg_models_proto_goTypes = nil
	file_meals_pkg_models_proto_depIdxs = nil
}
