// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: meals-pkg-service.proto

package meals_pkg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MealDeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MealUuid      []byte                 `protobuf:"bytes,1,opt,name=meal_uuid,json=mealUuid,proto3" json:"meal_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MealDeleteReq) Reset() {
	*x = MealDeleteReq{}
	mi := &file_meals_pkg_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MealDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MealDeleteReq) ProtoMessage() {}

func (x *MealDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_meals_pkg_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MealDeleteReq.ProtoReflect.Descriptor instead.
func (*MealDeleteReq) Descriptor() ([]byte, []int) {
	return file_meals_pkg_service_proto_rawDescGZIP(), []int{0}
}

func (x *MealDeleteReq) GetMealUuid() []byte {
	if x != nil {
		return x.MealUuid
	}
	return nil
}

type MealGetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MealUuid      []byte                 `protobuf:"bytes,1,opt,name=meal_uuid,json=mealUuid,proto3" json:"meal_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MealGetReq) Reset() {
	*x = MealGetReq{}
	mi := &file_meals_pkg_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MealGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MealGetReq) ProtoMessage() {}

func (x *MealGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_meals_pkg_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MealGetReq.ProtoReflect.Descriptor instead.
func (*MealGetReq) Descriptor() ([]byte, []int) {
	return file_meals_pkg_service_proto_rawDescGZIP(), []int{1}
}

func (x *MealGetReq) GetMealUuid() []byte {
	if x != nil {
		return x.MealUuid
	}
	return nil
}

type MealsEmpty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MealsEmpty) Reset() {
	*x = MealsEmpty{}
	mi := &file_meals_pkg_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MealsEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MealsEmpty) ProtoMessage() {}

func (x *MealsEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_meals_pkg_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MealsEmpty.ProtoReflect.Descriptor instead.
func (*MealsEmpty) Descriptor() ([]byte, []int) {
	return file_meals_pkg_service_proto_rawDescGZIP(), []int{2}
}

var File_meals_pkg_service_proto protoreflect.FileDescriptor

const file_meals_pkg_service_proto_rawDesc = "" +
	"\n" +
	"\x17meals-pkg-service.proto\x12\x06models\x1a\x16meals-pkg-models.proto\",\n" +
	"\rMealDeleteReq\x12\x1b\n" +
	"\tmeal_uuid\x18\x01 \x01(\fR\bmealUuid\")\n" +
	"\n" +
	"MealGetReq\x12\x1b\n" +
	"\tmeal_uuid\x18\x01 \x01(\fR\bmealUuid\"\f\n" +
	"\n" +
	"MealsEmpty2\xe4\x01\n" +
	"\fMealsService\x128\n" +
	"\x13CreateOrUpdateMeals\x12\r.models.Meals\x1a\x12.models.MealsEmpty\x12-\n" +
	"\bGetMeals\x12\x12.models.Pagination\x1a\r.models.Meals\x122\n" +
	"\x0eMealByMealUuid\x12\x12.models.MealGetReq\x1a\f.models.Meal\x127\n" +
	"\n" +
	"DeleteMeal\x12\x15.models.MealDeleteReq\x1a\x12.models.MealsEmptyB\x15Z\x13protocols/meals-pkgb\x06proto3"

var (
	file_meals_pkg_service_proto_rawDescOnce sync.Once
	file_meals_pkg_service_proto_rawDescData []byte
)

func file_meals_pkg_service_proto_rawDescGZIP() []byte {
	file_meals_pkg_service_proto_rawDescOnce.Do(func() {
		file_meals_pkg_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meals_pkg_service_proto_rawDesc), len(file_meals_pkg_service_proto_rawDesc)))
	})
	return file_meals_pkg_service_proto_rawDescData
}

var file_meals_pkg_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_meals_pkg_service_proto_goTypes = []any{
	(*MealDeleteReq)(nil), // 0: models.MealDeleteReq
	(*MealGetReq)(nil),    // 1: models.MealGetReq
	(*MealsEmpty)(nil),    // 2: models.MealsEmpty
	(*Meals)(nil),         // 3: models.Meals
	(*Pagination)(nil),    // 4: models.Pagination
	(*Meal)(nil),          // 5: models.Meal
}
var file_meals_pkg_service_proto_depIdxs = []int32{
	3, // 0: models.MealsService.CreateOrUpdateMeals:input_type -> models.Meals
	4, // 1: models.MealsService.GetMeals:input_type -> models.Pagination
	1, // 2: models.MealsService.MealByMealUuid:input_type -> models.MealGetReq
	0, // 3: models.MealsService.DeleteMeal:input_type -> models.MealDeleteReq
	2, // 4: models.MealsService.CreateOrUpdateMeals:output_type -> models.MealsEmpty
	3, // 5: models.MealsService.GetMeals:output_type -> models.Meals
	5, // 6: models.MealsService.MealByMealUuid:output_type -> models.Meal
	2, // 7: models.MealsService.DeleteMeal:output_type -> models.MealsEmpty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_meals_pkg_service_proto_init() }
func file_meals_pkg_service_proto_init() {
	if File_meals_pkg_service_proto != nil {
		return
	}
	file_meals_pkg_models_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meals_pkg_service_proto_rawDesc), len(file_meals_pkg_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_meals_pkg_service_proto_goTypes,
		DependencyIndexes: file_meals_pkg_service_proto_depIdxs,
		MessageInfos:      file_meals_pkg_service_proto_msgTypes,
	}.Build()
	File_meals_pkg_service_proto = out.File
	file_meals_pkg_service_proto_goTypes = nil
	file_meals_pkg_service_proto_depIdxs = nil
}
