// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: meals-pkg-models.proto

package meals_pkg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Meal struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	MealUuid              []byte                 `protobuf:"bytes,1,opt,name=meal_uuid,json=mealUuid,proto3" json:"meal_uuid,omitempty"`
	LocationUuid          []byte                 `protobuf:"bytes,2,opt,name=location_uuid,json=locationUuid,proto3" json:"location_uuid,omitempty"`
	Name                  string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description           string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Category              *Category              `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	MainIngredients       []*Ingredient          `protobuf:"bytes,6,rep,name=main_ingredients,json=mainIngredients,proto3" json:"main_ingredients,omitempty"`
	AdditionalIngredients []*Ingredient          `protobuf:"bytes,7,rep,name=additional_ingredients,json=additionalIngredients,proto3" json:"additional_ingredients,omitempty"`
	Tags                  []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	Weight                float32                `protobuf:"fixed32,9,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Meal) Reset() {
	*x = Meal{}
	mi := &file_meals_pkg_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Meal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meal) ProtoMessage() {}

func (x *Meal) ProtoReflect() protoreflect.Message {
	mi := &file_meals_pkg_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meal.ProtoReflect.Descriptor instead.
func (*Meal) Descriptor() ([]byte, []int) {
	return file_meals_pkg_models_proto_rawDescGZIP(), []int{0}
}

func (x *Meal) GetMealUuid() []byte {
	if x != nil {
		return x.MealUuid
	}
	return nil
}

func (x *Meal) GetLocationUuid() []byte {
	if x != nil {
		return x.LocationUuid
	}
	return nil
}

func (x *Meal) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Meal) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Meal) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *Meal) GetMainIngredients() []*Ingredient {
	if x != nil {
		return x.MainIngredients
	}
	return nil
}

func (x *Meal) GetAdditionalIngredients() []*Ingredient {
	if x != nil {
		return x.AdditionalIngredients
	}
	return nil
}

func (x *Meal) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Meal) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubCategories []*Category            `protobuf:"bytes,1,rep,name=sub_categories,json=subCategories,proto3" json:"sub_categories,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_meals_pkg_models_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_meals_pkg_models_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_meals_pkg_models_proto_rawDescGZIP(), []int{1}
}

func (x *Category) GetSubCategories() []*Category {
	if x != nil {
		return x.SubCategories
	}
	return nil
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Ingredient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price         float32                `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ingredient) Reset() {
	*x = Ingredient{}
	mi := &file_meals_pkg_models_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ingredient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ingredient) ProtoMessage() {}

func (x *Ingredient) ProtoReflect() protoreflect.Message {
	mi := &file_meals_pkg_models_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ingredient.ProtoReflect.Descriptor instead.
func (*Ingredient) Descriptor() ([]byte, []int) {
	return file_meals_pkg_models_proto_rawDescGZIP(), []int{2}
}

func (x *Ingredient) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Ingredient) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type Meals struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meals         []*Meal                `protobuf:"bytes,1,rep,name=Meals,proto3" json:"Meals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Meals) Reset() {
	*x = Meals{}
	mi := &file_meals_pkg_models_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Meals) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meals) ProtoMessage() {}

func (x *Meals) ProtoReflect() protoreflect.Message {
	mi := &file_meals_pkg_models_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meals.ProtoReflect.Descriptor instead.
func (*Meals) Descriptor() ([]byte, []int) {
	return file_meals_pkg_models_proto_rawDescGZIP(), []int{3}
}

func (x *Meals) GetMeals() []*Meal {
	if x != nil {
		return x.Meals
	}
	return nil
}

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_meals_pkg_models_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_meals_pkg_models_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_meals_pkg_models_proto_rawDescGZIP(), []int{4}
}

func (x *Pagination) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Pagination) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

var File_meals_pkg_models_proto protoreflect.FileDescriptor

const file_meals_pkg_models_proto_rawDesc = "" +
	"\n" +
	"\x16meals-pkg-models.proto\x12\x06models\"\xe2\x02\n" +
	"\x04Meal\x12\x1b\n" +
	"\tmeal_uuid\x18\x01 \x01(\fR\bmealUuid\x12#\n" +
	"\rlocation_uuid\x18\x02 \x01(\fR\flocationUuid\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12,\n" +
	"\bcategory\x18\x05 \x01(\v2\x10.models.CategoryR\bcategory\x12=\n" +
	"\x10main_ingredients\x18\x06 \x03(\v2\x12.models.IngredientR\x0fmainIngredients\x12I\n" +
	"\x16additional_ingredients\x18\a \x03(\v2\x12.models.IngredientR\x15additionalIngredients\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x12\x16\n" +
	"\x06weight\x18\t \x01(\x02R\x06weight\"W\n" +
	"\bCategory\x127\n" +
	"\x0esub_categories\x18\x01 \x03(\v2\x10.models.CategoryR\rsubCategories\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"6\n" +
	"\n" +
	"Ingredient\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x02R\x05price\"+\n" +
	"\x05Meals\x12\"\n" +
	"\x05Meals\x18\x01 \x03(\v2\f.models.MealR\x05Meals\":\n" +
	"\n" +
	"Pagination\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offsetB\x15Z\x13protocols/meals-pkgb\x06proto3"

var (
	file_meals_pkg_models_proto_rawDescOnce sync.Once
	file_meals_pkg_models_proto_rawDescData []byte
)

func file_meals_pkg_models_proto_rawDescGZIP() []byte {
	file_meals_pkg_models_proto_rawDescOnce.Do(func() {
		file_meals_pkg_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meals_pkg_models_proto_rawDesc), len(file_meals_pkg_models_proto_rawDesc)))
	})
	return file_meals_pkg_models_proto_rawDescData
}

var file_meals_pkg_models_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_meals_pkg_models_proto_goTypes = []any{
	(*Meal)(nil),       // 0: models.Meal
	(*Category)(nil),   // 1: models.Category
	(*Ingredient)(nil), // 2: models.Ingredient
	(*Meals)(nil),      // 3: models.Meals
	(*Pagination)(nil), // 4: models.Pagination
}
var file_meals_pkg_models_proto_depIdxs = []int32{
	1, // 0: models.Meal.category:type_name -> models.Category
	2, // 1: models.Meal.main_ingredients:type_name -> models.Ingredient
	2, // 2: models.Meal.additional_ingredients:type_name -> models.Ingredient
	1, // 3: models.Category.sub_categories:type_name -> models.Category
	0, // 4: models.Meals.Meals:type_name -> models.Meal
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_meals_pkg_models_proto_init() }
func file_meals_pkg_models_proto_init() {
	if File_meals_pkg_models_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meals_pkg_models_proto_rawDesc), len(file_meals_pkg_models_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meals_pkg_models_proto_goTypes,
		DependencyIndexes: file_meals_pkg_models_proto_depIdxs,
		MessageInfos:      file_meals_pkg_models_proto_msgTypes,
	}.Build()
	File_meals_pkg_models_proto = out.File
	file_meals_pkg_models_proto_goTypes = nil
	file_meals_pkg_models_proto_depIdxs = nil
}
